# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish Package
      run: |
        python -m twine upload --repository testpypi dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}              
    - name: TOML Reader       
      uses: SebRollen/toml-action@v1.0.2  
      id: read_toml
      with:
        file: 'pyproject.toml'
        field: 'project.version'
    - name: Get Latest Release
      uses: pozetroninc/github-action-get-latest-release@v0.7.0
      with:
        repository: ${{ github.repository }}
    - name: Edit Release
      uses: irongut/EditRelease@v1.2.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        id: ${{github.event.release.id}}
        body: "**PyPI Page: **test.pypi.org/manage/project/dijkstras-algorithm-TOMG-A/release/${{steps.read_toml.outputs.value}}"
            
            
